"""
EN PYTHON LOS ERRORES SE CONOCEN COMO EXCEPCIONES, CUANDO OCURRE UN ERROR DURANTE LA EJECUCIÓN DE UN PROGRAMA
PYTHON GENERA UNA EXCEPCION PARA NOTIFICAR QUE ALGO INESPERADO SUCEDIÓ. SI NO SE MANEJAN ADECUADAMENTE, ESTAS EXCEPCIONES PUEDEN DETENER LA EJECUCIÓN DEL PROGRAMA.
VAMOS A IR MIRANDO LOS PRINCIPALES ERRORES QUE PODEMOS ENCONTRAR CON PYTHON, CÓMO PROVOCARLOS Y CÓMO EVITARLOS
"""

#1.SyntaxError
#ESTE ERROR OCURRE CUANDO EL CÓDIGO NO SIGUE LA SINTAXIS VÁLIDA DE PYTHON. PUEDE SER CAUSADO POR PARÉNTESIS, COMAS, INDENTACIÓN INCORRECTA...

"""
if x > 5     #Falta dos puntos ':' para completar el if
    print("El valor es mayor que 5")

LA CONSOLA NOS MUESTRA: SyntaxError: expected ':'
"""

#2.NameError
#ESTE ERROR OCURRE CUANDO INTENTAS UTILIZAR UNA VARIABLE O FUNCIÓN QUE NO HA SIDO DEFINIDA PREVIAMENTE. 

"""
print(mensaje)  # La variable 'mensaje' no ha sido definida previamente

LA CONSOLA NOS MUESTRA: NameError: name 'mensaje' is not defined
"""

#3.IndexError
#ESTE ERROR OCURRE CUANDO INTENTAS ACCEDER A UN ÍNDICE QUE ESTÁ FUERA DEL RANGO DE UNA LISTA O SECUENCIA
#ESTE ERROR ES MUY COMÚN EN LOOPS YA QUE NO CONTROLAMOS BIEN EL TAMAÑO DE LAS LISTAS, DICCIONARIOS,SETS O CUALQUIER ESTRUCTURA DE DATOS
#E INTENTAMOS ACCEDER A POSICIONES DE MEMORIA QUE NO TENEMOS CONTROLADAS
#LAS POSICIONES VAN DESDE 0 HASTA N-1
#MI CONSEJO Y EXPERIENCIA DICEN QUE CUANDO TENGAMOS ESTE ERROR REVISEMOS LAS CONDICIONES DE NUESTROS BUCLES, ITERADORES ETC PORQUE VAN A ESTAR MAL PRÁCTICAMENTE SIEMPRE

"""
lista = [1, 2, 3]
print(lista[5])  # La lista tiene solo 3 elementos, no existe el índice 5

LA CONSOLA NOS MUESTRA: IndexError: list index out of range
"""

#4.ModuleNotFoundError
#ESTE ERROR SE PRODUCE CUANDO INTENTAS IMPORTAR UNA LIBRERÍA QUE NO EXISTE EN EL SISTEMA O QUE NO SE ENCUENTRA EN EL PATH DE BÚSQUEDA DE LIBRERÍAS DE PYTHON

"""
import mathss
LA FORMA CORRECTA SERÍA: 
import math

LA CONSOLA NOS MUESTRA: IndexError: No module named 'mathss'
"""

#5.AttributeError
#ESTE ERROR ES UNA EXCEPCIÓN ESPECÍFICA DE PYTHON QUE SE GENERA CUANDO INTENTAS ACCEDER A UN ATRIBUTO O MÉTODO QUE NO EXISTE EN UN OBJETO.
"""
import math
print(math.PI)
NUESTRA LIBRERÍA MATH TIENE UN ATRIBUTO pi que devuelve el valor de pi 3,1415...
PERO SI INTENTAMOS ACCEDER A PI QUE NO EXISTE VEREMOS ESTO POR CONSOLA:
AttributeError: module 'math' has no attribute 'PI'. Did you mean: 'pi'? Y NOS RECOMIENDA LO MÁS PARECIDO
"""

#6.KeyError
#ES UN ERROR QUE SE GENERA CUANDO INTENTAS ACCEDER A UNA CLAVE DE UN DICCIONARIO QUE NO EXISTE.
"""
my_dict = {'a': 1, 'b': 2, 'c': 3}
print(my_dict['d']) 
PARA EVITARLO PODEMOS USAR TRY EXCEPT Y CAPTURAR LA EXCEPCION
try:
    value = my_dict['d']
except KeyError:
    print("La clave 'd' no existe en el diccionario.")

"""

#7.TypeError
#ES UNA EXCEPCION QUE SE PRODUCE CUANDO SE INTENTA REALIZAR UNA OPERACIÓN EN UN TIPO DE DATO INCORRECTO O INCOMPATIBLE EN PYTHON.
#POR EJEMPLO INTENTAR SUMAR UN ENTERO CON UNA CADENA
"""
numero = 5
cadena = "10"
resultado = numero + cadena  
"""



#REVISAR







